# -*- coding: utf-8 -*-
"""Wine Classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h2oxihO2kBKshVXUIVnPJbEyz1maw7Al
"""

# Load Data
from google.colab import files
uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(name=fn,length=len(uploaded[fn])))
arquivo = "C:/ML/Vinhos/wine_dataset.csv"

import pandas as pd
import io

arquivo = pd.read_csv(io.StringIO(uploaded['wine_dataset.csv'].decode('utf-8')))

arquivo.shape

arquivo.head()

# Change Text labels to Numeric Labels
arquivo['style'] = arquivo['style'].replace('red', 0)
arquivo['style'] = arquivo['style'].replace('white', 1)

# Separando as variaveis entre preditoras e alvo (y = coluna style e x = todas as outras)
y = arquivo['style']
x = arquivo.drop('style', axis = 1)

from sklearn.model_selection import train_test_split

# Criando os conjuntos de dados de treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

from sklearn.ensemble import ExtraTreesClassifier
# Criacao do Modelo
modelo = ExtraTreesClassifier(n_estimators=100)

# Treinando o Modelo
modelo.fit(x_treino, y_treino)

# Imprimindo Resultados
resultado = modelo.score(x_teste, y_teste)
print("Acuracia: ", resultado)

y_teste[400:403]

x_teste[400:403]

previsoes = modelo.predict(x_teste[400:403])

previsoes